# Generated by Django 2.2 on 2021-05-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210517_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='current_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='goal_weight',
            field=models.IntegerField(blank=True),
        ),
    ]
